// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrhxbiiavhkuxjtfvivb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyaHhiaWlhdmhrdXhqdGZ2aXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDE4ODUsImV4cCI6MjA3NzgxNzg4NX0.qtLF65mrjKhhcEsT1r6S9L79eSoPEncGRny9mkauV1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
